/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_sudoku_window (void);
GtkWidget* create_filechooserdialog1 (void);
GtkWidget* create_geometry_dialog (void);
GtkWidget* create_aboutbox (void);
